#!/usr/bin/env ruby

require "fileutils"
require "pathname"
require "shellwords"
include FileUtils::Verbose

class Pathname
  alias_method :/, :+ unless method_defined?(:/)
end

OS = RUBY_PLATFORM =~ /darwin/ ? :osx : :linux
HOSTNAME = `hostname`.chomp
ROOT = Pathname.new(__FILE__).parent.expand_path
DOTFILES_HOME = ROOT/"home"
HOME = Pathname.new(Dir.home)

def system(*args)
  puts args.shelljoin
  super
end

def link_files(src_dir, dst_dir, options = {})
  mkdir_p dst_dir unless dst_dir.directory?
  src_dir.children.each do |file|
    next if options.fetch(:skip_directory, true) && file.directory?
    ln_sf file, dst_dir
  end
end

## Install oh-my-zsh
unless (HOME/".oh-my-zsh").exist?
  system "curl -L http://install.ohmyz.sh | sh"
  @omz_fresh_install = true
end

## Install tmux-plugins
unless (HOME/".tmux/plugins/tpm").exist?
  system "git", "clone", "https://github.com/tmux-plugins/tpm", "#{HOME}/.tmux/plugins/tpm"
  @tpm_fresh_install = true
end

# Link files
link_files(DOTFILES_HOME, HOME)
link_files(DOTFILES_HOME/".config", HOME/".config", skip_directory: false)
link_files(DOTFILES_HOME/".oh-my-zsh/custom", HOME/".oh-my-zsh/custom")
link_files(DOTFILES_HOME/".ssh", HOME/".ssh") unless HOSTNAME =~ /.*\.comp\.hkbu\.edu\.hk/
ln_sf DOTFILES_HOME/".brew-aliases", HOME

## Post linking
system "lesskey"
unless @omz_fresh_install
  ENV["ZSH"] = "#{HOME}/.oh-my-zsh"
  system "/bin/sh $ZSH/tools/upgrade.sh"
end
if @tpm_fresh_install
  system "#{HOME}/.tmux/plugins/tpm/scripts/install_plugins.sh", "--shell-echo"
else
  system "#{HOME}/.tmux/plugins/tpm/scripts/update_plugin.sh", "--shell-echo", "all"
end
