#!/usr/bin/env ruby
# rubocop:disable Layout/SpaceAroundOperators, Style/GlobalVars, Style/MixinUsage, Lint/MissingCopEnableDirective
# frozen_string_literal: true

require "fileutils"
require "optparse"
require "pathname"

OS = `uname`.chomp
ROOT = Pathname.new(__dir__).expand_path
HOME = Pathname.new(Dir.home)
DOTFILES_HOME = ROOT/"home"
HOSTS_DIR = ROOT/"hosts"

$opt = {
  dry_run: false,
  host: nil,
}
OptionParser.new do |parser|
  parser.banner = "Usage: setup [options]"
  parser.on("-H", "--host HOST", "Host to be setup") do |host|
    $opt[:host] = host
  end
  parser.on("-d", "--dry-run", "Dry run") do |dry_run|
    $opt[:dry_run] = dry_run
  end
  parser.on_tail("-h", "--help", "Show this message") do
    puts parser.help
    exit
  end
end.parse!

if $opt[:dry_run]
  warn "==> Dry run mode."
  include FileUtils::DryRun
else
  include FileUtils::Verbose
end

def mac?
  OS == "Darwin"
end

def symlink_target(path)
  target = path.readlink
  target = (path.dirname/target).cleanpath unless target.absolute?
  target.cleanpath
end

def inside?(path, directory)
  path == directory || path.to_s.start_with?("#{directory}/")
end

def managed_symlink?(path)
  path.symlink? && inside?(symlink_target(path), ROOT)
end

def host_root
  HOSTS_DIR/$opt[:host] if $opt[:host]
end

def link_entry(source_path, destination_dir)
  mkdir_p destination_dir unless destination_dir.directory?
  return if source_path.basename.to_s == ".DS_Store"

  ln_sf source_path, destination_dir
end

def link_host_override(shared_path, host_path, destination_dir)
  if shared_path.directory? && host_path.directory? && !managed_symlink?(shared_path)
    host_path.children.sort.each do |child|
      link_host_override shared_path/child.basename, child, destination_dir/host_path.basename
    end
  else
    link_entry host_path, destination_dir
  end
end

def link_tree(name, skip_child_dir: false)
  destination_dir = HOME/name

  # Link shared files
  shared_path = DOTFILES_HOME/name
  if shared_path.file?
    link_entry shared_path, destination_dir
  elsif shared_path.directory?
    shared_path.children.sort.each do |child|
      next if skip_child_dir && child.directory?

      link_entry child, destination_dir
    end
  end

  # Link host override
  return unless $opt[:host]

  host_path = host_root/name
  if host_path.file?
    link_entry host_path, destination_dir
  elsif host_path.directory?
    host_path.children.sort.each do |child|
      next if skip_child_dir && child.directory?

      link_host_override shared_path/child.basename, child, destination_dir
    end
  end
end

def remove_stale_links(path)
  if path.directory?
    path.children.sort.each { |child| remove_stale_links child }
    return
  end

  return unless managed_symlink?(path)

  if path.exist?
    target = symlink_target(path)
    return unless inside?(target, HOSTS_DIR)

    rm path if $opt[:host].nil? || !inside?(target, host_root)
  else
    rm path
  end
end

def clean_tree(name)
  directory = HOME/name
  return unless directory.exist?

  directory.children.sort.each do |child|
    next unless managed_symlink? child

    remove_stale_links child
  end
end

$opt[:host] = "mac" if $opt[:host].nil? && mac?

# Link
link_tree ".", skip_child_dir: true
link_tree ".config"
link_tree ".gnupg"
link_tree ".ssh"
link_tree ".local/bin"
link_tree ".local/share/cargo"
link_entry HOME/".config/Code/User", HOME/"Library/Application Support/Code" if mac?

# Cleanup broken symlinks
clean_tree "."
clean_tree ".config"
clean_tree ".gnupg"
clean_tree ".ssh"
clean_tree ".local/bin"
clean_tree ".local/share/cargo"

# Post linking
chmod 0o700, HOME/".ssh"
chmod 0o600, (HOME/".ssh/config").realpath if (HOME/".ssh/config").exist?
chmod 0o700, HOME/".gnupg"
