#!/usr/bin/env ruby
# rubocop:disable Layout/SpaceAroundOperators, Style/MixinUsage, Style/NumericLiteralPrefix

require "fileutils"
require "pathname"
require "shellwords"
include FileUtils::Verbose

class Pathname
  alias / + unless method_defined?(:/)
  alias to_str to_s unless method_defined?(:to_str)
end

HOSTNAME = `hostname`.chomp
ROOT = Pathname.new(__dir__).expand_path
DOTFILES_HOME = ROOT/"home"
DOTFILES_HOME_CSR = ROOT/"home_csr"
HOME = Pathname.new(Dir.home)

def system(*args)
  puts args.shelljoin
  super
end

def link_files(src_dir, dst_dir, skip_directory: true)
  mkdir_p dst_dir unless dst_dir.directory?
  src_dir.children.sort.each do |file|
    next if skip_directory && file.directory?
    next if file.basename.to_s == ".DS_Store"

    ln_sf file, dst_dir
  end
end

def clean(dir)
  dir.children.sort.each do |file|
    next if file.exist?
    next unless file.symlink?

    rm file if file.readlink.to_s.start_with? ROOT.to_s
  end
end

def csr?
  HOSTNAME =~ /.*\.comp\.hkbu\.edu\.hk/ || HOSTNAME =~ /^csr\d+/
end

def mac?
  `uname`.chomp == "Darwin"
end

# Link files
link_files(DOTFILES_HOME, HOME)
link_files(DOTFILES_HOME/".config", HOME/".config", skip_directory: false)
link_files(DOTFILES_HOME/".local/bin", HOME/".local/bin")
link_files(DOTFILES_HOME/".local/share/cargo", HOME/".local/share/cargo")

if csr?
  link_files(DOTFILES_HOME_CSR, HOME)
  link_files(DOTFILES_HOME_CSR/".ssh", HOME/".ssh")
else
  link_files(DOTFILES_HOME/".ssh", HOME/".ssh")
end

if mac?
  link_files(DOTFILES_HOME/".gnupg", HOME/".gnupg")
  mkdir_p HOME/"Library/Application Support/Code"
  ln_sf DOTFILES_HOME/".config/vscode/User",
        HOME/"Library/Application Support/Code"
else
  mkdir_p HOME/".gnupg"
  ln_sf DOTFILES_HOME/".gnupg/gpg.conf", HOME/".gnupg"
end

# Cleanup broken symlinks
clean(HOME)
clean(HOME/".config")
clean(HOME/".ssh")
clean(HOME/".gnupg")

# Post linking
chmod 0700, HOME/".ssh"
chmod 0600, (HOME/".ssh/config").realpath
chmod 0700, HOME/".gnupg"

ENV["LESSKEY"] = "#{ENV["HOME"]}/.local/share/less/lesskey"
mkdir_p HOME/".local/share/less"
system "lesskey", HOME/".config/less/lesskey"
