" Load plugins
source ~/.nvim/plugins.vim
" Load basic settings
source ~/.nvim/basic.vim
" Load key mapping
source ~/.nvim/keymap.vim
" Load plugins settings
for f in split(glob('~/.nvim/pluginrc.d/*.vim'), '\n')
  exe 'source' f
endfor
