" Set vim-home
let g:vim_home = $HOME . '/.nvim/'
" Load plugins
execute 'source' g:vim_home . 'plugins.vim'
" Load basic settings
execute 'source' g:vim_home . 'basic.vim'
" Load key mapping
execute 'source' g:vim_home . 'keymap.vim'
" Load plugins settings
for f in split(glob(g:vim_home . 'pluginrc.d/*.vim'), '\n')
  execute 'source' f
endfor
