tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
brew "aria2"
brew "atool"
brew "autojump"
brew "bat"
brew "boost"
brew "fontconfig"
brew "sqlite"
brew "python"
brew "swig"
brew "ccls"
brew "ckan"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "cpanminus"
brew "cryptopp"
brew "ctags"
brew "direnv"
brew "exa"
brew "exiftool"
brew "fd"
brew "gmp"
brew "ffmpeg"
brew "fpp"
brew "fzf"
brew "gcc"
brew "ghostscript"
brew "gistit"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnupg"
brew "gnuplot"
brew "graphviz"
brew "hexyl"
brew "htop"
brew "httpie"
brew "hub"
brew "icdiff"
brew "imagemagick"
brew "jq"
brew "languagetool"
brew "less"
brew "librsvg"
brew "mas"
brew "mitmproxy"
brew "mupdf-tools"
brew "neovim"
brew "node"
brew "pandoc"
brew "pbc"
brew "perl"
brew "pinentry-mac"
brew "pipenv"
brew "pyenv"
brew "pyenv-which-ext"
brew "pygments"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "safe-rm"
brew "shellcheck"
brew "ssh-copy-id"
brew "tcping"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "tor"
brew "unrar"
brew "xsv"
brew "yarn"
brew "you-get"
brew "youtube-dl"
brew "zsh-syntax-highlighting"
cask "1password"
cask "adoptopenjdk"
cask "alfred"
cask "bartender"
cask "cheatsheet"
cask "coconutbattery"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-hack-nerd-font"
cask "font-noto-sans-cjk"
cask "font-noto-serif-cjk"
cask "forklift"
cask "grammarly"
cask "iina"
cask "intel-power-gadget"
cask "istat-menus"
cask "iterm2"
cask "jump-desktop"
cask "keybase"
cask "logitech-options"
cask "logitech-presentation"
cask "mactex"
cask "mark-text"
cask "mcedit"
cask "minecraft"
cask "motrix"
cask "numi"
cask "paw"
cask "pdfexpert"
cask "plex-media-server"
cask "presentation"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlrest"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "skim"
cask "skype"
cask "steam"
cask "terminology"
cask "vagrant"
cask "visual-studio-code"
cask "vmware-fusion"
cask "webpquicklook"
mas "Amphetamine", id: 937984704
mas "Archiver", id: 619437121
mas "Dropshelf", id: 540404405
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1480793815
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LimeChat", id: 414030210
mas "Mate Translate", id: 1005088137
mas "MathStudio", id: 829912893
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Moom", id: 419330170
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Orangered Notifier", id: 468366517
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "PopClip", id: 445189367
mas "QQ", id: 451108668
mas "ReadKit", id: 588726889
mas "Roadblock", id: 1051436753
mas "Scan", id: 722364523
mas "Sip", id: 507257563
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telegram", id: 747648890
mas "TunesArt", id: 444696268
mas "Wallpaper Wizard", id: 1266674560
mas "WeChat", id: 836500024
mas "WhatsApp", id: 1147396723
mas "WiFi Explorer", id: 494803304
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
