#!/usr/bin/env ruby

require "tempfile"

Dir.mktmpdir("latexindent") do |dir|
  file = "#{dir}/input.tex"
  config = "#{dir}/localSettings.yaml"
  File.write(file, $stdin.read)
  File.write(config, 'defaultIndent: "    "')
  IO.popen(["latexindent", "-l", file, *ARGV]) do |io|
    puts io.read.gsub(/[ \t]+$/, "")
  end
end
