#!/usr/bin/env ruby

require "open3"

hosts = %w[
  github.com
  bitbucket.com
  lab.xuc.me
  haibo.server.xuc.me
]

csrs = (30..31).to_a + (38..69).to_a
comp_hosts = %w[faith] + csrs.map { |h| "csr#{h}" }
hosts += comp_hosts
hosts += comp_hosts.map { |h| "#{h}.comp.hkbu.edu.hk" }

new = hosts.map do |h|
  o, _s = Open3.capture2("ssh-keyscan", "-H", h)
  o.strip
end.compact.join("\n")

File.write("#{ENV["HOME"]}/.ssh/known_hosts", new)
